---
- name: Provision a single robot image
  hosts: default
  tasks:
  - name: Install desired packages
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - vim
    update_cache: true
    become: true

  - name: Install necessary packages
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - python-rosdep
      - ca-certificates
    update_cache: true
    become: true
  - name: Run rosdep init
    command: rosdep init
    become: true
