---
- name: Provision a single robot image
  hosts: "/mnt/bare_metal"
  environment:
    HOME: "/home/{{ ansible_user }}"
  tasks:
  - name: Install desired packages
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - vim
    become: true
